version: '3'

services:
   web:
     build: .
     environment:
       REDIS_URL: tcp://localhost:61616
     depends_on:
       - activemq
     ports:
       - "8080:8080"

   activemq:
     image: webcenter/activemq:5.14.3
