# run this file using "docker-compose up -d
version: '3'

services:
   web:
     build: .
     environment:
       REDIS_URL: tcp://localhost:61616
     depends_on:
       - activemq
     ports:
       - "8080:8080"

   activemq:
     image: webcenter/activemq:5.14.3

   prometheus:
      image: prom/prometheus:v2.0.0
      ports:
        - 9090:9090
      volumes:
        - monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus_data:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
      depends_on:
        - node-exporter

    node-exporter:
      image: prom/node-exporter:v0.15.1
      ports:
        - 9100:9100
      volumes:
        - /proc:/host/proc
        - /sys:/host/sys
        - /:/rootfs
      command:
        - "--path.procfs=/host/proc"
        - "--path.sysfs=/host/sys"
        - "--collector.textfile.directory=/etc/node-exporter/"
        - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

    grafana:
      image: grafana/grafana:4.3.2
      ports:
        - 3000:3000
      depends_on:
        - prometheus
      volumes:
        - grafana_data:/var/lib/grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_USERS_ALLOW_SIGN_UP=false
