server:
  address: 0.0.0.0
queue:
  name: ${QUEUE_NAME:mainQueue}
worker:
  name: ${HOSTNAME:worker1}
  enabled: ${WORKER_ENABLED:true}
store:
  enabled: ${STORE_ENABLED:true}
spring:

activemq:
    in-memory: true
    brokerUrl: ${ACTIVEMQ_BROKER_URL:vm://localhost:61616}