server:
  address: 0.0.0.0
  port: 8080
queue:
  name: ${QUEUE_NAME:mainQueue}
worker:
  name: ${HOSTNAME:worker1}
  enabled: ${WORKER_ENABLED:true}
store:
  enabled: ${STORE_ENABLED:true}

activemq:
#    in-memory: true
    brokerUrl: ${ACTIVEMQ_BROKER_URL:vm://localhost:61616}


