# run this file using "docker-compose up -d
version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  backend:
    container_name: hpa-backend
    image: spring-boot-hpa3:latest
    ports:
           - "31000:8080"
#           - "8001:8000"
    environment:
            - ACTIVEMQ_BROKER_URL=tcp://queue:61616
#           - ACTIVEMQ_BROKER_URL=tcp://0.0.0.0:61616
#           - ACTIVEMQ_BROKER_URL=vm://localhost:61616
            - STORE_ENABLED=false
            - WORKER_ENABLED=true
    depends_on:
       - queue


  frontend:
    container_name: hpa-frontend
    image: spring-boot-hpa3:latest
    ports:
           - "32000:8080"
#           - "8002:8000"
    environment:
            - ACTIVEMQ_BROKER_URL=tcp://queue:61616
#           - ACTIVEMQ_BROKER_URL=tcp://0.0.0.0:61616
#           - ACTIVEMQ_BROKER_URL=vm://localhost:61616
            - STORE_ENABLED=true
            - WORKER_ENABLED=false
    depends_on:
       - queue


  queue:
    container_name: queue
    image: webcenter/activemq:5.14.3
    ports:
      - "61616:61616"



  node-exporter:
    container_name: hpa-xport
    image: prom/node-exporter:v0.15.1
    ports:
        - 9100:9100
    volumes:
        - /proc:/host/proc
        - /sys:/host/sys
        - /:/rootfs
    command:
        - "--path.procfs=/host/proc"
        - "--path.sysfs=/host/sys"
        - "--collector.textfile.directory=/etc/node-exporter/"
        - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'


  prometheus:
      container_name: hpa-prom
      image: prom/prometheus:v2.0.0
      ports:
        - 9090:9090
      volumes:
        - ./prometheus-cfg1.yml:/etc/prometheus/prometheus-cfg1.yml
        - prometheus_data:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus-cfg1.yml'
        - '--storage.tsdb.path=/prometheus'
      depends_on:
        - node-exporter

  grafana:
      container_name: hpa-grafana
      image: grafana/grafana:4.3.2
      ports:
        - 3000:3000
      depends_on:
        - prometheus
      volumes:
        - grafana_data:/var/lib/grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_USERS_ALLOW_SIGN_UP=false